version: 1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout

      - restore_cache:
          keys:
            - nuget-{{ checksum "src/BlockChyp/BlockChyp.csproj" }}

      - run:
          name: Build
          command: make build

      - run:
          name: Test
          command: make test

      - save_cache:
          key: nuget-{{ checksum "src/BlockChyp/BlockChyp.csproj" }}
          paths:
            - $HOME/.nuget/packages

      - persist_to_workspace:
          root: src/BlockChyp/bin
          paths:
            - Release/*

  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - attach_workspace:
          at: src/BlockChyp/bin

      - run:
          name: Publish
          command: make publish

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
