version: 1
jobs:
  build:
    docker:
      # This image doesn't have GNU make, so we just call commands directly
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout

      - restore_cache:
          keys:
            - nuget-{{ checksum "src/BlockChyp/BlockChyp.csproj" }}

      - run: dotnet restore -v n

      - save_cache:
          key: nuget-{{ checksum "src/BlockChyp/BlockChyp.csproj" }}
          paths:
            - $HOME/.nuget/packages

      - run:
          name: Build
          command: |
            dotnet build src/BlockChyp/BlockChyp.csproj -c Release -v n
            dotnet pack src/BlockChyp/BlockChyp.csproj -c Release -v n

      - run:
          name: Test
          command: >
            dotnet test tests/BlockChypTest/BlockChypTest.csproj
            --filter "Category!=Integration" -v n

      - persist_to_workspace:
          root: src/BlockChyp/bin
          paths:
            - Release/*

  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - attach_workspace:
          at: src/BlockChyp/bin

      - run:
          name: Publish
          command: >
            dotnet nuget push src/BlockChyp/bin/Release/BlockChyp.*.nupkg
            --api-key "${NUGET_API_KEY}"
            --source https://api.nuget.org/v3/index.json

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
